#!/bin/env perl
use strict;
use warnings;
use IO::File;
use Crypt::ECDH_ES qw(ecdhes_encrypt);

die 'usage: encrypt <public_key_file> <plaintext>'
    unless @ARGV == 2;

my $fh = IO::File->new($ARGV[0], 'r')
    or die "error reading public key from $ARGV[0] ", $!, "\n";
my $public_key = $fh->getline;
$fh->close;
chomp($public_key);

print unpack('H*', Crypt::ECDH_ES::ecdhes_encrypt(pack('H*', $public_key), $ARGV[1]));
